import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import UserInfo from '../components/UserInfo'
import CardContainer from '../components/CardContainer'
import pageData from '@/components/data'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [lang, setLang] = useState('es')
  const [information, setInformation] = useState([])
  const [cards, setCards] = useState([])

  const setLangEsp =  () => {
    setLang('es')
  }

  const setLangEng =  () => {
    setLang('en')
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <UserInfo eng={setLangEng} esp={setLangEsp} info={pageData[lang].signIn}/>
          <CardContainer cardsText={pageData[lang].cards}/>
        </div>
      </main> 
    </>
  )
}
